# Generated by Django 3.2.12 on 2022-04-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reting',
            new_name='rating',
        ),
    ]
